void __json_printSpanningTree_HEAP_NODE(HEAP_NODE* root, FILE *treeF, FILE *outerF, int *nodeCount, int *outer_exist){ if(!root)return;
     *outer_exist = 0;
     *nodeCount = 0;
     typedef struct QUEUE { HEAP_NODE *node;
     struct QUEUE *next;
 } QUEUE;
 QUEUE *queueTemp = ((void *)0), *queueRoot = ((void *)0), *queueTail = ((void *)0);
 HEAP_NODE *theNode;
 root->arg = malloc(sizeof(int));
 *(int *)root->arg = (*nodeCount)++;
 fprintf(treeF,"            {");
 fprintf(treeF," \"id\":%d",*(int *)root->arg);
 fprintf(treeF,",\"parentId\":\"\"");
 fprintf(treeF,",\"linkData\":");
HEAP_NODE_fprintLinkD(treeF,((void *)0),root);
 fprintf(treeF,",\"nodeData\":");
 HEAP_NODE_fprintNodeD(treeF,root);
 fprintf(treeF,"},\n");
 theNode = root;
 while(1){ int theNodeChildCount = HEAP_NODE_getChildCount(theNode);
     for(int i = 0;
     i < theNodeChildCount;
     i++){ HEAP_NODE *child = HEAP_NODE_getChild(theNode,i);
     if(!child) continue;
     if(!child->arg){ child->arg = malloc(sizeof(int));
     *(int *)child->arg = (*nodeCount)++;
     if(queueTail) queueTail = queueTail->next = (QUEUE*)malloc(sizeof(QUEUE));
     else queueTail = queueRoot = (QUEUE*)malloc(sizeof(QUEUE));
     queueTail->node = child;
     queueTail->next = ((void *)0);
     fprintf(treeF,"            {");
     fprintf(treeF," \"id\":%d",*(int *)child->arg);
     fprintf(treeF,",\"parentId\":%d",*(int *)theNode->arg);
     fprintf(treeF,",\"linkData\":");
     HEAP_NODE_fprintLinkD(treeF,theNode,child);
     fprintf(treeF,",\"nodeData\":");
     HEAP_NODE_fprintNodeD(treeF,child);
     fprintf(treeF,"},\n");
 } else { *outer_exist = 1;
     fprintf(outerF,"            {");
     fprintf(outerF," \"id\":%d",*(int *)child->arg);
     fprintf(outerF,",\"parentId\":%d",*(int *)theNode->arg);
     fprintf(outerF,",\"linkData\":");
     HEAP_NODE_fprintLinkD(outerF,theNode,child);
     fprintf(outerF,"},\n");
 } } if(queueRoot){ theNode = queueRoot->node;
     if(queueRoot->next){ queueTemp = queueRoot;
     queueRoot = queueRoot->next;
     free(queueTemp);
 }else{ free(queueRoot);
     queueTail = queueRoot = ((void *)0);
 } } else break;
 } HEAP_NODE_clearArg(root);
}